name: Build and Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
        
    - name: Install UI dependencies
      run: |
        cd ui
        bun install
        bun run build
        cd ..
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: iwhitebird/rtsp-stream-app:latest
        cache-from: type=registry,ref=iwhitebird/rtsp-stream-app:buildcache
        cache-to: type=registry,ref=iwhitebird/rtsp-stream-app:buildcache,mode=max 